all: earnings

earnings: earnings.cpp utility.cpp max-heap.cpp
	g++ -o earnings earnings.cpp utility.cpp max-heap.cpp

utility: utility.cpp
	g++ -o utility.o utility.cpp

max-heap: max-heap.cpp
	g++ -o max-heap max-heap.cpp

binary-search-tree: binary-search-tree.cpp
	g++ -o binary-search-tree binry-search-tree.cpp

hash-table: hash-table.cpp
	g++ -o hash-table hash-table.cpp